name: CI
on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  build-linux-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq libsdl2-dev libglew-dev
      - name: build ded
        run: |
          ./build.sh
        env:
          CC: gcc
  build-linux-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq libsdl2-dev libglew-dev
      - name: build ded
        run: |
          ./build.sh
        env:
          CC: clang
  build-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: brew install sdl2 pkg-config glew
      - name: build ded
        run: |
          ./build.sh
        env:
          CC: clang
  build-windows-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Install dependencies
        run: |
          ./setup_dependencies.bat
      - name: build ded
        shell: cmd
        run: |
          ./build_msvc.bat
      - name: Prepare WindowsBinaries artifacts
        shell: cmd
        run: |
          mkdir winbin
          copy /B *.exe winbin
          copy /B *.dll winbin
          copy /B *.ttf winbin
          xcopy shaders winbin\shaders\
      - name: Upload WindowsBinaries artifacts
        uses: actions/upload-artifact@v3
        with:
          name: WindowsBinaries
          path: ./winbin/
